システム構築
SunriseDigital/magazine pull request #1
Opened 2017-07-28 06:30 UTC by tkabeee

2017-07-28 08:00 UTC, tkabeee commented
## システムのファイル構成

```
/home/source/sites/magazine
|-- application
|   |-- controllers
|   |   |-- cli
|   |   |   `-- ErrorController.php
|   |   |-- default
|   |   |   |-- ErrorController.php
|   |   |   |-- IndexController.php
|   |   |   `-- MagazineController.php
|   |   `-- mobile
|   |       |-- ErrorController.php
|   |       |-- IndexController.php
|   |       `-- MagazineController.php
|   |-- views
|   `-- web
|       |-- index.php
|       `-- mobile_index.php
|-- common
|   |-- config
|   |   `-- sys.yml
|   |-- css
|   |-- js
|   |-- models
|   |   `-- Site
|   |       |-- Configuration.php
|   |       |-- Controller
|   |       |   |-- Action
|   |       |   |   |-- Http
|   |       |   |   |   |-- Mobile.php
|   |       |   |   |   `-- Pc.php
|   |       |   |   `-- Http.php
|   |       |   `-- Plugin
|   |       |       |-- Http
|   |       |       |   |-- Mobile.php
|   |       |       |   `-- Pc.php
|   |       |       `-- Http.php
|   |       `-- Environment
|   |           |-- Cli.php
|   |           |-- Http
|   |           |   |-- Mobile.php
|   |           |   `-- Pc.php
|   |           `-- Http.php
|   |-- plugins
|   |   `-- smarty
|   `-- views
`-- README.md
```

2017-08-02 07:59 UTC, tkabeee commented
## システムのファイル構成

https://github.com/SunriseDigital/magazine/pull/1#issuecomment-318588135
前回の構成から更にcopy用ディレクトリを作成して、その中にVIEWとConfig、フロントコントローラのソースファイルを追加してみました

```bash
/home/source/sites/magazine
|-- application
|   |-- controllers
|   |   |-- cli
|   |   |   `-- ErrorController.php
|   |   |-- default
|   |   |   |-- ErrorController.php
|   |   |   |-- IndexController.php
|   |   |   `-- MagazineController.php
|   |   `-- mobile
|   |       |-- ErrorController.php
|   |       |-- IndexController.php
|   |       `-- MagazineController.php
|   |-- views
|   `-- web
|       |-- index.php
|       `-- mobile_index.php
|-- common
|   |-- config
|   |   `-- sys.yml
|   |-- css
|   |-- img
|   |-- js
|   |-- models
|   |   `-- Site
|   |       |-- Configuration.php
|   |       |-- Controller
|   |       |   |-- Action
|   |       |   |   |-- Http
|   |       |   |   |   |-- Mobile.php
|   |       |   |   |   `-- Pc.php
|   |       |   |   `-- Http.php
|   |       |   `-- Plugin
|   |       |       |-- Http
|   |       |       |   |-- Mobile.php
|   |       |       |   `-- Pc.php
|   |       |       `-- Http.php
|   |       `-- Environment
|   |           |-- Cli.php
|   |           |-- Http
|   |           |   |-- Mobile.php
|   |           |   `-- Pc.php
|   |           `-- Http.php
|   |-- plugins
|   |   `-- smarty
|   `-- views
|-- copy
|   |-- config
|   |   |-- Configuration.php
|   |   |-- magazine
|   |   |   |-- category.yml
|   |   |   |-- group.yml
|   |   |   `-- list.yml
|   |   |-- mobile_route.yml
|   |   |-- route.yml
|   |   `-- sys.yml
|   |-- gitignore
|   |-- views
|   |   |-- default
|   |   |   |-- error
|   |   |   |   |-- 404.tpl
|   |   |   |   `-- 500.tpl
|   |   |   |-- index
|   |   |   |   `-- index.tpl
|   |   |   `-- magazine
|   |   |       |-- article
|   |   |       |   `-- 1
|   |   |       |       |-- body.tpl
|   |   |       |       `-- outline.tpl
|   |   |       |-- article.tpl
|   |   |       |-- base.tpl
|   |   |       |-- category.tpl
|   |   |       |-- group.tpl
|   |   |       `-- index.tpl
|   |   |-- i18n
|   |   `-- mobile
|   |       |-- error
|   |       |   |-- 404.tpl
|   |       |   `-- 500.tpl
|   |       |-- index
|   |       |   `-- index.tpl
|   |       `-- magazine
|   |           |-- article.tpl
|   |           |-- base.tpl
|   |           |-- category.tpl
|   |           |-- group.tpl
|   |           `-- index.tpl
|   `-- web
|       |-- htaccess
|       |-- index.php
|       `-- mobile_index.php
|-- initapp
`-- README.md
```

2017-08-03 06:26 UTC, gomo requested changes

2017-08-03 06:26 UTC, gomo commented on initapp
> +sdx_dir="/home/source/sites/sdx"
これはルートからのパスが決め打ちになるし、sourceやsitesというのはどのLINUXに元からあるものでは無いのでよろしく無いですね。

sdxのパスも渡すのがいいのかな？

あるいはinitappのパスからmagazineのパスがわかると思うので、magazineと並列な場所にsdxが無いとダメ、というルールにするのもありですが・・・

まあ、パス渡す方がいいですかね？

😇

2017-08-03 06:26 UTC, gomo commented on initapp
> +#/path/to/initapp /path/to/target_dir /path/to/context_dir
target_dirとcontext_dirというのはニュアンスが少し違うと思うのでコメントを変更しておいてもらえますでしょうか？コードないの痴漢もそんなに大変じゃないと思うのでしておいてもらおうかな。

何がいいかね？

/path/to/web_dir
/path/to/app_dir
/path/to/sdx_dir

でどうでしょうか？

😇

2017-08-08 09:58 UTC, tkabeee commented on initapp
> +#/path/to/initapp /path/to/target_dir /path/to/context_dir
> /path/to/web_dir
/path/to/app_dir
/path/to/sdx_dir

それぞれ引数のパスを表すテキストを上記の例通りに変更しました。
シェル内の変数名も合わせるように修正しております。

2017-08-08 10:00 UTC, tkabeee commented on initapp
> +sdx_dir="/home/source/sites/sdx"
3つ目の引数に sdx のパスを指定するように変更しました。

変更後の初期化コマンドは、下記のようになります。
```shell
/path/to/initapp /path/to/web_dir /path/to/app_dir /path/to/sdx_dir
```

2017-08-10 04:03 UTC, gomo approved these changes
👍

2017-10-11 05:34 UTC, katsuji-anzai commented
👍 
OKです。

2017-10-19 01:48 UTC, merged